
#define ID_TIMER                    200



// define these if not defined by 'scrnsave.h' (for NT only)

#ifndef IDS_DESCRIPTION
#define IDS_DESCRIPTION      1
#endif /* IDS_DESCRIPTION */

#ifndef idsIsPassword
#define idsIsPassword           1000
#endif /* idsIsPassword */

#ifndef idsPassword
#define idsPassword             1003
#endif /* idsPassword */

#ifndef idsDifferentPW
#define idsDifferentPW          1004
#endif /* idsDifferentPW */

#ifndef idsChangePW
#define idsChangePW             1005
#endif /* idsChangePW */

#ifndef idsBadOldPW
#define idsBadOldPW             1006
#endif /* idsBadOldPW */
