//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by sftshell.rc
//


#define IDM_ABOUT            256

#define IDM_OPEN_MENU        257
#define IDM_STATUS_BAR       258
#define IDM_ASSOCIATE_MENU   259

#define IDM_EXIT             261

#define IDM_COPY_MENU        262
#define IDM_PASTE_MENU       263
#define IDM_EDIT_CMDLINE     264
#define IDM_HELP_COMMAND     265
#define IDM_HELP_KEYS        266
#define IDM_COPY_ALL         267
#define IDM_PAGE_UP          268
#define IDM_PAGE_DOWN        269
#define IDM_CTRL_RIGHT       270
#define IDM_CTRL_LEFT        271

#define IDM_CMD_LIST         272
#define IDM_CMD_EDIT         273
#define IDM_CMD_ORIGINAL     274
#define IDM_CMD_SELECTED     275
#define IDM_REGISTRATION     276

#define IDM_CTRL_UP          277
#define IDM_CTRL_DOWN        278
#define IDM_STATUS           279
#define IDM_EXTERR           280
#define IDM_CBRK             281
#define IDM_CTRL_S           282
#define IDM_CTRL_Q           283

#define IDM_CTRL_HOME        284
#define IDM_CTRL_END         285

#define IDM_HELP_VARIABLES   286
#define IDM_COPY_CMDLINE     287
#define IDM_PRINT_MENU       288

#define IDM_FONT7x5          289
#define IDM_FONT8x6          290
#define IDM_FONT12x8         291
#define IDM_FONT16x12        292
#define IDM_FONT24x18        293
#define IDM_FONT32x24        294
#define IDM_FONT_NORMAL      295

#define IDM_HELP_ANSI        296

#define IDC_EXTENSION        297
#define IDC_ASSOCIATE        298
#define IDC_APPLIST          299
#define IDC_BROWSE           300
#ifndef IDC_HELP
 #define IDC_HELP             301
#endif // IDC_HELP
#define IDM_HELP_CALCULATION 302

#define IDM_DOWN             303
#define IDM_UP               304
#define IDM_RIGHT            305
#define IDM_LEFT             306
#define IDM_INSERT           307
#define IDM_DELETE           308
#define IDM_CMDLINE          309
#define IDM_HOME             310
#define IDM_END              311

#define IDM_TOOL_BAR         312
#define IDM_QUEUE_MENU       313
#define IDM_FONT_MENU        314
#define IDM_FOLDER_MENU      315

#define IDC_FORMAT_QUEUE     316
#define IDC_SUSPEND_FORMAT   317
#define IDC_RESUME_FORMAT    318
#define IDC_REMOVE_FORMAT    319

#define IDC_COPY_QUEUE       320
#define IDC_SUSPEND_COPY     321
#define IDC_RESUME_COPY      322
#define IDC_REMOVE_COPY      323

#define IDC_PATH             324
#define IDC_DIRLIST          325
#define IDC_DRIVELIST        326

#define IDM_ERASEHISTORY     327
#define IDM_FONT9x7          328
#define IDM_FONT48x36        329

#define SFTSHELL_FONT        330
#define FONTFILE             331

#define IDM_SCREEN_LINES     332
#define IDC_SPIN_UP          333
#define IDC_SPIN_DOWN        334
#define IDC_LINES            335

#define IDM_INSTANT_BATCH    336
#define IDC_BATCH_TEXT       337



// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        501
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           338
#endif
#endif
