/***************************************************************************/
/*                                                                         */
/*  TOILET.H - header file for a 'toilet' icon for 'dumping trash' into.   */
/*                                                                         */
/***************************************************************************/


#define IDM_FLUSH           0x1000
#define IDM_UNDELETE        0x1001
#define IDM_ABOUT           0x1002
#define IDM_INFRONT         0x1003
#define IDM_SETUP           0x1004

#define IDM_RESTORE         129
#define IDM_RESTOREALL      130
#define IDM_PURGE           131
#define IDM_LISTBOX         132
#define IDM_BRIEFHELP       133
#define IDM_OPENICON        134
#define IDM_FULLICON        135
#define IDM_SHUTICON        136
#define IDM_OPENICON_NAME   137
#define IDM_FULLICON_NAME   138
#define IDM_SHUTICON_NAME   139
#define IDM_WAVEFILE_NAME   140
#define IDM_DROPWAVE_NAME   141
#define IDM_ICONCAPTION     142
#define IDM_HIDDENPATH_NAME 143
#define IDM_OPENICON_NAME2  144
#define IDM_FULLICON_NAME2  145
#define IDM_SHUTICON_NAME2  146
#define IDM_WAVEFILE_NAME2  147
#define IDM_DROPWAVE_NAME2  148
